In [6]:
import random
import numpy as np


class Board:
    def __init__(self, n):
        self.n_queen = n
        self.map = [[0 for j in range(n)] for i in range(n)]
        self.fit = 0

    def set_queens(self):
        for i in range(self.n_queen):
            j = random.randint(0, self.n_queen - 1)
            self.map[i][j] = 1

    def fitness(self):
        self.fit = self.n_queen * (self.n_queen - 1) // 2
        for i in range(self.n_queen):
            for j in range(self.n_queen):
                if self.map[i][j] == 1:
                    for k in range(1, self.n_queen - i):
                        if self.map[i + k][j] == 1:
                            self.fit -= 1
                        if j - k >= 0 and self.map[i + k][j - k] == 1:
                            self.fit -= 1
                        if j + k < self.n_queen and self.map[i + k][j + k] == 1:
                            self.fit -= 1
                            
    def encode(self):
        s = ''
        for row in self.map:
            for i in range(len(row)):
                if row[i] == 1:
                    s += str(i)
                    break
        return s

    
    def show(self):
        print(np.matrix(self.map))
        print("Fitness: ",  self.fit)

        
if __name__ == '__main__':
    test = Board(5)
    test.set_queens()
    test.fitness()
    test.show()
    print(test.encode())

[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [1 0 0 0 0]]
Fitness:  4
33430


In [2]:
class Hill_Climb:
    
    def __init__(self, n):
        self.step = 0
        self.map = n
        self.q_pos = set()  
    
    def moveQueen(self):
        temp = self.map.map[0]
        self.map.map[0] = [0,0,0,0,0]
        mfit = 0
        mindx = 0
        for i in range(5):
            self.map.map[i] = [0,0,0,0,0]
            mfit = 0
            mindx = 0
            for j in range(5):
                self.map.map[i][j] = 1
                self.map.fitness()
                if(self.map.fit > mfit):
                    mfit = self.map.fit
                    mindx = j
                self.map.map[i][j] = 0
                if(mfit == 10):
                    print("Finished")
                    self.map.fitness()
                    self.map.show()
                    return self
            self.map.map[i][mindx] = 1
        self.moveQueen()
        
if __name__ == '__main__':
    home = Board(5)
    home.set_queens()
    home.fitness()
    home.show()
    print("\n")
    climb = Hill_Climb(home)
    climb.moveQueen()
        
    

[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]
Fitness:  4


Finished
[[0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
Fitness:  10


In [5]:
class Genetic:
    def __init__(self, n):
        self.step = 0

        
    def solve(self):
        r = np.random.randint(0, 101) / 100
        print(r)
        

if __name__ == '__main__':
    home = Board(5)
    home.solve()
    home.show()

AttributeError: 'Board' object has no attribute 'solve'