In [18]:
import random
import numpy as np


class Board:
    def __init__(self, n):
        self.n_queen = n
        self.map = [[0 for j in range(n)] for i in range(n)]
        #I added it queen positions
        self.q_pos = dict()
        self.fit = 0

    def set_queens(self):
        for i in range(self.n_queen):
            j = random.randint(0, self.n_queen - 1)
            self.map[i][j] = 1
            self.q_pos[i]=j

    def fitness(self):
        self.fit = self.n_queen * (self.n_queen - 1) // 2
        for i in range(self.n_queen):
            for j in range(self.n_queen):
                if self.map[i][j] == 1:
                    for k in range(1, self.n_queen - i):
                        if self.map[i + k][j] == 1:
                            self.fit -= 1
                        if j - k >= 0 and self.map[i + k][j - k] == 1:
                            self.fit -= 1
                        if j + k < self.n_queen and self.map[i + k][j + k] == 1:
                            self.fit -= 1

    def show(self):
        print(np.matrix(self.map))
        print("Fitness: ",  self.fit)
        print("Queen Positions: ", self.q_pos)

        
if __name__ == '__main__':
    test = Board(5)
    test.set_queens()
    test.fitness()
    test.show()

[[1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]]
Fitness:  5
Queen Positions:  {0: 0, 1: 1, 2: 0, 3: 1, 4: 3}


In [24]:
class Hill_Climb:
    
    def __init__(self, n, q):
        self.step = 0
        self.map = n
        self.q_pos = q
       
    def getQueenPos(self):
        h = []
        for items in self.q_pos.items():
            pos = [items[1],items[2]]
    
    def checkHorizontal(self,pos):
        return 0
        
        return 1
        
    def checkDiagonal(self,pos):
        return 0
        
        return 1
        
    def checkVertical(self,pos):
        return 0
        
        return 1
    
    def show(self):
        print(np.matrix(self.map))

if __name__ == '__main__':
    home = Board(5)
    home.set_queens()
    home.show()
    print("\n")
    climb = Hill_Climb(home.map,home.q_pos)
    climb.show()
    climb.getQueenPos()
        
    

[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]
Fitness:  0
Queen Positions:  {0: 4, 1: 1, 2: 3, 3: 1, 4: 1}


[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]
0 4
1 1
2 3
3 1
4 1


In [14]:
class Genetic:
    def __init__(self, n):
        self.step = 0


if __name__ == '__main__':
    home = Board(5)
    home.show()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Fitness:  0
